// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(FinalProjectContext))]
    [Migration("20190719003933_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Exotic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Manufacturer");

                    b.Property<decimal>("Model");

                    b.Property<string>("Picture");

                    b.Property<string>("SubModel");

                    b.Property<int>("Vin");

                    b.HasKey("Id");

                    b.ToTable("Exotic");
                });

            modelBuilder.Entity("FinalProject.Models.Muscle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Manufacture");

                    b.Property<decimal>("Model");

                    b.Property<string>("Picture");

                    b.Property<string>("SubModel");

                    b.HasKey("Id");

                    b.ToTable("Muscle");
                });

            modelBuilder.Entity("FinalProject.Models.Tuner", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Model");

                    b.Property<string>("Picture");

                    b.Property<string>("SubModel");

                    b.Property<string>("Vin");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Tuner");
                });
#pragma warning restore 612, 618
        }
    }
}
